name: Nuclei - Vulnerability Scan Dev Branch

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Nuclei - Vulnerability Scan
        if: github.ref == 'refs/heads/dev' && github.event_name == 'schedule'
        id: nuclei_scan
        uses: projectdiscovery/nuclei-action@main
        with:
          target: https://www.staging.packtpub.com

      - name: GitHub Workflow artifacts
        if: github.ref == 'refs/heads/dev' && github.event_name == 'schedule'
        uses: actions/upload-artifact@v4
        with:
          name: nuclei.log
          path: nuclei.log
