name: Nuclei - Vulnerability Scan Dev Branch

on:
    schedule:
      - cron: '*/5 * * * *'
    workflow_dispatch:

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
       steps:
      - uses: actions/checkout@v4
      - name: Get current branch name
        id: get_branch
        run: echo "branch_name=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Check branch
        run: |
          if [[ "$GITHUB_ENV" != "dev" && "$GITHUB_ENV" != "dev" ]]; then
            echo "Not on staging or dev branch. Exiting."
            exit 0
          fi

      - name: Nuclei - Vulnerability Scan
        id: nuclei_scan
        uses: projectdiscovery/nuclei-action@main
        with:
          target: https://www.staging.packtpub.com

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuclei.log
          path: nuclei.log

      
