# .github/workflows/run-linux-command.yml
name: Run Linux Command

on: 
  push:
    branches:
      - master  # Trigger on pushes to the main branch
  workflow_dispatch:  # Allows for manual triggering  

jobs:
  run-linux-command:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a Linux command
        run: |
          echo "Running a Linux command"
          ls -alh  # Example command: lists files in the directory with detailed view
          uname -a  # Example command: displays system information
          df -h  # Example command: shows disk space usage
          date
