name: Nuclei Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  nuclei:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nuclei
        run: |
          curl -sSfL https://install.projectdiscovery.io | sh

      - name: Run Nuclei
        run: nuclei -u https://www.packtpub.com/ -json -o nuclei-results.json

      - name: Upload results to DefectDojo
        run: |
          curl -X POST "${{ secrets.DOJO_URL }}/api/v2/import-scan/" \
            -H "Authorization: Token ${{ secrets.DOJO_API_TOKEN }}" \
            -F 'scan_type=Nuclei Scan' \
            -F 'engagement=${{ secrets.DOJO_ENGAGEMENT_ID }}' \
            -F 'file=@nuclei-results.json'
