name: Dast Nuclei → DefectDojo

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  nuclei:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nuclei
        run: |
          curl -sSfL https://install.projectdiscovery.io | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run Nuclei
        run: nuclei -u https://www.packtpub.com/ -json -o nuclei-results.json

      - name: Upload results to DefectDojo
        run: |
          curl -X POST "${{ secrets.DOJO_URL }}/api/v2/import-scan/" \
            -H "Authorization: Token ${{ secrets.DOJO_API_TOKEN }}" \
            -F 'scan_type=Nuclei Scan' \
            -F "engagement=${{ secrets.DOJO_ENGAGEMENT_ID }}" \
            -F 'file=@nuclei-results.json'
