name: Nuclei - DAST Scan

on:
    schedule:
      - cron: '40 11 * * *'
    workflow_dispatch:

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Nuclei - DAST Scan
        uses: projectdiscovery/nuclei-action@dev
        with:
          target: https://epic.packtpub.com

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nuclei.log
          path: nuclei.log
