name: Secret Scan tools Trufflehog
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  trufflehog_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install TruffleHog
        run: pip install trufflehog

      - name: Run TruffleHog
        run: trufflehog --json --repo_path . > trufflehog_report.json

      - name: Upload results to DefectDojo
        run: |
          curl -X POST "${{ secrets.DOJO_URL }}/api/v2/import-scan/" \
            -H "Authorization: Token ${{ secrets.DOJO_API_TOKEN }}" \
            -F 'scan_type=Nuclei Scan' \
            -F "engagement=${{ secrets.DOJO_ENGAGEMENT_ID }}" \
            -F 'file=@trufflehog_report.json'
