name: SAST with Semgrep (v1.135.0) & DefectDojo

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  sast-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Semgrep Latest
        run: python3 -m pip install --upgrade semgrep==1.135.0

      - name: Run Semgrep Scan
        run: semgrep --config=p/security-audit --json --error . > semgrep-report.json

      - name: Send report to DefectDojo
        run: |
          curl -X POST "${{ secrets.DEFECTDOJO_URL }}/api/v2/import-scan/" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
            -F "file=@semgrep-report.json" \
            -F "scan_type=Semgrep JSON Report" \
            -F "product=${{ secrets.DEFECTDOJO_PRODUCT_ID }}" \
            -F "engagement=${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}" \
            -F "active=true" \
            -F "verified=false"
