name: SAST with Semgrep (v1.135.0) & DefectDojo

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  sast-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Semgrep v1.135.0
        run: python3 -m pip install --upgrade semgrep==1.135.0

      - name: Run Semgrep Scan
        run: |
          semgrep --config=p/security-audit --json . --error --json-output semgrep-report.json

      - name: Upload results to DefectDojo
        run: |
          curl -X POST "${{ secrets.DOJO_URL }}/api/v2/import-scan/" \
            -H "Authorization: Token ${{ secrets.DOJO_API_TOKEN }}" \
            -H "Content-Type: multipart/form-data" \
            -F 'scan_type=Semgrep JSON Report' \
            -F "engagement=${{ secrets.DOJO_ENGAGEMENT_ID }}" \
            -F "auto_create_context=true" \
            -F "active=true" \
            -F "verified=false" \
            -F "file=@semgrep-report.json"
