name: SAST with Semgrep (v1.135.0) & DefectDojo

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  sast-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Semgrep Latest
        run: python3 -m pip install --upgrade semgrep==1.135.0

      - name: Run Semgrep Scan
        run: semgrep --config=p/security-audit --json . > semgrep-report.json

      - name: Upload results to DefectDojo
        run: |
          curl -X POST "${{ secrets.DOJO_URL }}/api/v2/import-scan/" \
            -H "Authorization: Token ${{ secrets.DOJO_API_TOKEN }}" \
            -F 'scan_type=Semgrep JSON Report' \
            -F "engagement=${{ secrets.DOJO_ENGAGEMENT_ID }}" \
            -F 'file=@semgrep-report.json'
            -F "active=true" \
            -F "verified=false"
      - name: Fail if high severity issues
        run: |
          HIGH_COUNT=$(jq '[.results[] | select(.extra.severity == "ERROR")] | length' semgrep-report.json)
          if [ "$HIGH_COUNT" -gt 0 ]; then
          echo "❌ High severity issues found: $HIGH_COUNT"
          exit 1
          fi
