name: workflow test name
on: workflow_dispatch
jobs:
  first-Job:
    runs-on: ubuntu
    steps:
      - name: echo test command
        run: echo "Hello world"
      - name: echo test 2
        run: echo "good bye"
